#!/bin/bash

fName="startup.dat"

# compile 
icc -O3 startup.cpp -o startup

# run
rm ${fName}; 

rset=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20)

for r in ${rset[@]}; do

	./startup | grep 'start-up' | tr -d '[A-Za-z:\-() \n]'  >> $fName
	echo -ne '\t' >> $fName

done



