#!/bin/bash

fName="stride.dat"

# compile 
make clean; make; 

# transfer 

scp -r ~/mic_bench/stride/ mic0:~/mic_bench/

# run
ssh mic0 "cd ~/mic_bench/stride/; rm $fName"
#rset=(1 2 3 4 5 6 7 8 9 10)
#for r in ${rset[@]}; do
ssh mic0 "cd ~/mic_bench/stride/; ./stride >> $fName"

ssh mic0 "cd ~/mic_bench/stride/; echo ' ' >> $fName"
#done
# download data

scp mic0:~/mic_bench/stride/$fName .

