#!/bin/bash

fName1t="rw1t.dat"
fName2t="rw2t.dat"
fName3t="rw3t.dat"
fName4t="rw4t.dat"

# compile 
cd ./rw1t; make clean; make; cd ../; 
cd ./rw2t; make clean; make; cd ../; 
cd ./rw3t; make clean; make; cd ../; 
cd ./rw4t; make clean; make; cd ../; 

# transfer
scp -r ~/mic_bench/cache_bw_saxpy mic0:~/mic_bench/

# remove history data records
ssh mic0 "cd ~/mic_bench/cache_bw_rw/; rm $fName1t $fName2t $fName3t $fName4t"

# run
rset=(1 2 3 4 5 6 7 8 9 10)
#rset=(1)
for r in ${rset[@]}; do
ssh mic0 "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/lib64/; export OMP_NUM_THREADS=1; export KMP_AFFINITY=granularity=fine,proclist=[1-239:1],explicit; cd ~/mic_bench/cache_bw_rw/; ./rw1t/cache_bw | grep 'cbw' | tr -d '[A-Za-z: \n]'  >> $fName1t"
ssh mic0 "cd ~/mic_bench/cache_bw_rw/; echo ' ' >> $fName1t"

ssh mic0 "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/lib64/; export OMP_NUM_THREADS=2; export KMP_AFFINITY=granularity=fine,proclist=[1-239:1],explicit; cd ~/mic_bench/cache_bw_rw/; ./rw2t/cache_bw | grep 'cbw' | tr -d '[A-Za-z: \n]'  >> $fName2t"
ssh mic0 "cd ~/mic_bench/cache_bw_rw/; echo ' ' >> $fName2t"

ssh mic0 "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/lib64/; export OMP_NUM_THREADS=3; export KMP_AFFINITY=granularity=fine,proclist=[1-239:1],explicit; cd ~/mic_bench/cache_bw_rw/; ./rw3t/cache_bw | grep 'cbw' | tr -d '[A-Za-z: \n]'  >> $fName3t"
ssh mic0 "cd ~/mic_bench/cache_bw_rw/; echo ' ' >> $fName3t"

ssh mic0 "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/lib64/; export OMP_NUM_THREADS=4; export KMP_AFFINITY=granularity=fine,proclist=[1-239:1],explicit; cd ~/mic_bench/cache_bw_rw/; ./rw4t/cache_bw | grep 'cbw' | tr -d '[A-Za-z: \n]'  >> $fName4t"
ssh mic0 "cd ~/mic_bench/cache_bw_rw/; echo ' ' >> $fName4t"

done

# download data
scp mic0:~/mic_bench/cache_bw_rw/$fName1t .
scp mic0:~/mic_bench/cache_bw_rw/$fName2t .
scp mic0:~/mic_bench/cache_bw_rw/$fName3t .
scp mic0:~/mic_bench/cache_bw_rw/$fName4t .





